import { Suspense } from 'react';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { FloatingCart } from '@/components/cart/floating-cart';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Poppins, Open_Sans } from 'next/font/google';

import 'swiper/css';

import './globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const openSans = Open_Sans({
  variable: '--font-open-sans',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${openSans.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <NuqsAdapter>
          {children}
          <Suspense fallback={null}>
            <FloatingCart />
          </Suspense>
          <Toaster richColors />
        </NuqsAdapter>
      </body>
    </html>
  );
}
